const { Router } = require('express')
const apiKeys = require('#modules/api-keys/api-keys.routes')
const auth = require('#modules/auth/auth.routes')
const chat = require('#modules/chat/chat-room.routes')
const friends = require('#modules/friends/friends.routes')
const game = require('#modules/game/game.routes')
const messages = require('#modules/messages/messages.routes')
const notifications = require('#modules/notifications/notifications.routes')
const publicApi = require('#modules/public/public.routes')
const system = require('#modules/system/system.routes')
const tournament = require('#modules/tournament/tournament.routes')
const users = require('#modules/users/users.routes')

const v1Router = Router()

v1Router.use('/', system)
v1Router.use('/api-keys', apiKeys)
v1Router.use('/auth', auth)
v1Router.use('/chat', chat)
v1Router.use('/users', users)
v1Router.use('/friends', friends)
v1Router.use('/game', game)
v1Router.use('/messages', messages)
v1Router.use('/notifications', notifications)
v1Router.use('/public', publicApi)
v1Router.use('/tournaments', tournament)

module.exports = v1Router
