ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "failedLoginCount" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "lockedOutUntil" TIMESTAMP(3);

ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "twoFactorChallengeVersion" INTEGER NOT NULL DEFAULT 0;
